spring:
  datasource:
    url: jdbc:h2:mem:testdb      # 메모리 모드 H2 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update            # create, create-drop, update 가능
    show-sql: true                # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true               # H2 콘솔 활성화
      path: /h2-console           # 콘솔 접근 경로
